
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async updateProfile(req: UpdateProfileReq) : Promise<Result<UserProfile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_profile", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendChat(req: LLMRequest) : Promise<Result<LLMResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFiles(dirPath: string | null) : Promise<Result<FileEntry[], FsError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_files", { dirPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(filePath: string) : Promise<Result<FileContent, FsError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(filePath: string, content: string) : Promise<Result<FileContent, FsError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { filePath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchCode(query: string) : Promise<Result<string[], FsError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_code", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readSkeleton(filePath: string) : Promise<Result<string, FsError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_skeleton", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runCommand(program: string, args: string[]) : Promise<Result<CommandOutput, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_command", { program, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAgentLoop(prompt: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_agent_loop", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTerminal(sessionId: string, input: string) : Promise<Result<null, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_terminal", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CommandOutput = { stdout: string; stderr: string; exit_code: number }
export type FileContent = { path: string; content: string }
export type FileEntry = { path: string; name: string; is_dir: boolean; children: FileEntry[] | null }
export type FsError = { Io: string } | "SecurityViolation" | "InvalidPath" | { Syntax: string }
export type LLMConfig = { api_key: string; base_url: string; model: string; temperature: number }
export type LLMRequest = { messages: Message[]; config: LLMConfig }
export type LLMResponse = { role: string; content: string; tool_calls: ToolCall[] | null; usage: Partial<{ [key in string]: number }> | null }
export type Message = { role: string; content: string }
export type ShellError = { Io: string } | { NotFound: string } | { Pty: string }
export type ToolCall = { name: string; arguments: Partial<{ [key in string]: string }> }
export type UpdateProfileReq = { name: string; bio: string }
export type UserProfile = { id: number; name: string; bio: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
